# I/O

In this example, we will show how to load various input types and to extract relevance informations

In [1]:
import numpy as np
from copy import deepcopy
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor

In [2]:
import sys
from pathlib import Path
ROOT = Path.cwd().parent.parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT)) 

from muonscripts.constants import constants
from muonscripts.io_tools.read import read_cif
from muonscripts.io_tools.read import read_from_file

import muonscripts.io_tools as ios
import muonscripts.io_tools.read_qe  as qe
import muonscripts.io_tools.read_elk  as elk

from muonscripts.io_tools.load_relax import load_relax
from muonscripts.io_tools.load_relax import save_relax_results
from muonscripts.io_tools.load_relax import load_relax_results
from muonscripts.io_tools.find_qe_files import select_groups
from muonscripts.io_tools.find_qe_files import get_relax_after_run
from muonscripts.io_tools.find_qe_files import print_relax_summary
from muonscripts.io_tools.find_qe_files import load_relax_from_folder

from muonscripts.muon_tools import contact_field


# ROOT, sys.path
print("Planck's Constant:", constants.H_PLANCK)

Planck's Constant: 6.62607015e-34


In [3]:
import os
dpath = './data'

load input structure formats

In [4]:
file=os.path.join(dpath, 'CaF2.cif')
read_cif(file)
read_from_file(file)

/home/misah/.virtualenvs/pyqm/lib/python3.10/site-packages/ase/io/cif.py:411: UserWarning: crystal system 'cubic' is not interpreted for space group Spacegroup(225, setting=1). This may result in wrong setting!
  warnings.warn(


Atoms(symbols='Ca4F8', pbc=True, cell=[5.45095, 5.45095, 5.45095], spacegroup_kinds=...)

In [5]:
file=os.path.join(dpath, 'CaF2.vasp')
read_cif(file)
read_from_file(file)

Atoms(symbols='Ca4F8', pbc=True, cell=[5.4509501457, 5.4509501457, 5.4509501457])

In [6]:
file=os.path.join(dpath, 'CaF2.vasp')
Structure.from_file(file)

Structure Summary
Lattice
    abc : 5.4509501457 5.4509501457 5.4509501457
 angles : 90.0 90.0 90.0
 volume : 161.96330486922204
      A : np.float64(5.4509501457) np.float64(0.0) np.float64(0.0)
      B : np.float64(0.0) np.float64(5.4509501457) np.float64(0.0)
      C : np.float64(0.0) np.float64(0.0) np.float64(5.4509501457)
    pbc : True True True
PeriodicSite: Ca (2.725, 2.725, 2.725) [0.5, 0.5, 0.5]
PeriodicSite: Ca (2.725, 0.0, 0.0) [0.5, 0.0, 0.0]
PeriodicSite: Ca (0.0, 2.725, 0.0) [0.0, 0.5, 0.0]
PeriodicSite: Ca (0.0, 0.0, 2.725) [0.0, 0.0, 0.5]
PeriodicSite: F (1.363, 4.088, 4.088) [0.25, 0.75, 0.75]
PeriodicSite: F (4.088, 1.363, 1.363) [0.75, 0.25, 0.25]
PeriodicSite: F (4.088, 1.363, 4.088) [0.75, 0.25, 0.75]
PeriodicSite: F (1.363, 4.088, 1.363) [0.25, 0.75, 0.25]
PeriodicSite: F (4.088, 4.088, 1.363) [0.75, 0.75, 0.25]
PeriodicSite: F (1.363, 1.363, 4.088) [0.25, 0.25, 0.75]
PeriodicSite: F (1.363, 1.363, 1.363) [0.25, 0.25, 0.25]
PeriodicSite: F (4.088, 4.088, 4.088) 

load QE input/output file

In [7]:
file = os.path.join(dpath, 'relax.in')
ios.read_qe.read_in(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [8]:
file = os.path.join(dpath, 'relax.out')
ios.read_qe.read_out(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.901900350679567, 10.901900350679567, 10.901900350679567], calculator=SinglePointDFTCalculator(...))

In [9]:
file = os.path.join(dpath, 'relax.in')
qe.read_in(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [10]:
file = os.path.join(dpath, 'relax.out')
qe.read_out(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.901900350679567, 10.901900350679567, 10.901900350679567], calculator=SinglePointDFTCalculator(...))

In [11]:
file = os.path.join(dpath, 'relax.in')
read_from_file(file, format='espresso-in')

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [12]:
file = os.path.join(dpath, 'relax.out')
atoms = read_from_file(file, format='espresso-out', index=-1)

convert ase to pymatgen

In [13]:
rlx = AseAtomsAdaptor.get_structure(atoms)
rlx

Structure Summary
Lattice
    abc : 10.901900350679567 10.901900350679567 10.901900350679567
 angles : 90.0 90.0 90.0
 volume : 1295.7064600901604
      A : np.float64(10.901900350679567) np.float64(0.0) np.float64(0.0)
      B : np.float64(0.0) np.float64(10.901900350679567) np.float64(0.0)
      C : np.float64(0.0) np.float64(0.0) np.float64(10.901900350679567)
    pbc : True True True
PeriodicSite: Ca (2.969, 2.969, 2.725) [0.2723, 0.2723, 0.25]
PeriodicSite: Ca (8.174, 8.174, 8.176) [0.7498, 0.7498, 0.75]
PeriodicSite: Ca (8.121, 8.121, 2.726) [0.7449, 0.7449, 0.25]
PeriodicSite: Ca (2.723, 2.723, 8.176) [0.2498, 0.2498, 0.75]
PeriodicSite: Ca (8.172, 2.729, 8.176) [0.7496, 0.2504, 0.75]
PeriodicSite: Ca (2.715, 8.182, 2.726) [0.2491, 0.7505, 0.25]
PeriodicSite: Ca (2.729, 8.172, 8.176) [0.2504, 0.7496, 0.75]
PeriodicSite: Ca (8.182, 2.715, 2.726) [0.7505, 0.2491, 0.25]
PeriodicSite: Ca (2.732, 5.477, 5.48) [0.2506, 0.5024, 0.5026]
PeriodicSite: Ca (8.151, -0.006704, -0.02879) [0.7

convert pymatgen to ase

In [14]:
file=os.path.join(dpath, 'CaF2.vasp')
st = Structure.from_file(file)
atoms = AseAtomsAdaptor.get_atoms(st)
atoms

MSONAtoms(symbols='Ca4F8', pbc=True, cell=[5.4509501457, 5.4509501457, 5.4509501457])

load QE efg tensors from gipaw output file

In [15]:
file = os.path.join(dpath, 'V3Si_QE_EFG3x3x3_SITE_A.OUT')
efg_tensors = qe.read_efg(file)

efg_tensors[0]

array([[-8.62804611e+19,  0.00000000e+00, -1.14694029e+20],
       [ 0.00000000e+00, -2.97322139e+20,  0.00000000e+00],
       [-1.14694029e+20,  0.00000000e+00,  3.83602600e+20]])

load ELK output files: (geometry and EFG tensors)

In [16]:
file = os.path.join(dpath, 'MnSi_GEOMETRY.OUT')
elk.read_geom(file)

Atoms(symbols='Mn4Si4', pbc=True, cell=[4.566199937664733, 4.566199937664733, 4.566199937664733], initial_magmoms=...)

In [17]:
file = os.path.join(dpath, 'MnSi_EFG.OUT')
efg_tensors = elk.read_efg(file)

efg_tensors[0]

array([[-3.02274846e+04, -1.54534901e+20, -1.54534901e+20],
       [-1.54534901e+20, -3.12190144e+05, -1.54534901e+20],
       [-1.54534901e+20, -1.54534901e+20,  3.42417629e+05]])

remove numerical noise in efg tensors

In [18]:
remove_efg_noise=True
efg_noise_threshold=1e-8

tensors = []
for tensor in efg_tensors:
    if remove_efg_noise:
        max_element = np.max(np.abs(tensor))
        if max_element > 0:
            tensor[np.abs(tensor) < efg_noise_threshold * max_element] = 0.0
    tensors.append(tensor)

tensors[0]

array([[ 0.00000000e+00, -1.54534901e+20, -1.54534901e+20],
       [-1.54534901e+20,  0.00000000e+00, -1.54534901e+20],
       [-1.54534901e+20, -1.54534901e+20,  0.00000000e+00]])

query ALL 'relax' muon site calculations from a folder

save to a file, if desired

In [19]:
folder = os.path.join(dpath, 'SZRO/query')

preview = True

pattern="*.out"
check_input = True
calc_types = "relax"


if preview:
    groups = get_relax_after_run(
        folder, 
        pattern=pattern, 
        check_input=check_input,
        calc_types=calc_types, 
        verbose=False,
    )
    print(f"\nPreview: {len(groups)} system group(s) found "
            f"(selection filters ignored in preview mode)\n")
    print_relax_summary(groups)


results = load_relax(
    path=folder,
    pattern=pattern,
    check_input=check_input,
    calc_types=calc_types,
    group_by_system=True,
    pymatgen=True,
    verbose=True,
    # **select_kwargs
)

file = 'SZRO_muonrelax_results.pkl'
file = os.path.join(dpath, file)
save_relax_results(results, file, fmt='pickle')


Preview: 1 system group(s) found (selection filters ignored in preview mode)

  H-O-Re-Sr-Zn  nat = 161  ntyp = 5  -> 12 converged runs
  ------------------------------------------
  1 distinct system(s), 12 converged run(s) total
Saved 12 result(s) to data/SZRO_muonrelax_results.pkl (pickle)


load results if present

In [20]:
file = 'SZRO_muonrelax_results.pkl'
file = os.path.join(dpath, file)

data = load_relax_results(file, fmt='pickle')

idx = 0
d = data[idx]

rlx_st = Structure.from_dict(d["rlxd_struct"])

In [21]:
rlx_st

Structure Summary
Lattice
    abc : 11.227995975740034 11.162596884469144 15.774003846053155
 angles : 90.0 90.06497345109028 90.0
 volume : 1977.0113052299323
      A : np.float64(11.227988756378162) np.float64(0.0) np.float64(-0.012732551982284818)
      B : np.float64(0.0) np.float64(11.162596884469144) np.float64(0.0)
      C : np.float64(0.0) np.float64(0.0) np.float64(15.774003846053155)
    pbc : True True True
PeriodicSite: Sr (2.815, 2.906, 1.982) [0.2507, 0.2603, 0.1258]
PeriodicSite: Sr (2.84, 2.908, 9.859) [0.2529, 0.2605, 0.6252]
PeriodicSite: Sr (2.818, 8.524, 1.939) [0.251, 0.7636, 0.1231]
PeriodicSite: Sr (2.842, 8.443, 9.843) [0.2531, 0.7563, 0.6242]
PeriodicSite: Sr (8.443, 2.909, 1.954) [0.752, 0.2606, 0.1245]
PeriodicSite: Sr (8.437, 2.884, 9.861) [0.7514, 0.2584, 0.6257]
PeriodicSite: Sr (8.418, 8.499, 1.949) [0.7497, 0.7614, 0.1241]
PeriodicSite: Sr (8.439, 8.47, 9.846) [0.7516, 0.7588, 0.6248]
PeriodicSite: Sr (-0.01497, 5.438, 5.945) [-0.001333, 0.4872, 0.3769]


compute spin density at muon site from QE (pp) .XSF file (up & down .xsf files)

In [22]:
up_file = 'Fe2P_QE_spinup.XSF'
up_file = os.path.join(dpath, up_file)
dw_file = 'Fe2P_QE_spindw.XSF'
dw_file = os.path.join(dpath, dw_file)

sp_density, B_c = contact_field.field_at_muon(up_file, dw_file)

print(f'calculated spin density at muon site = {sp_density: .6e} (bohr^-3) | contact field = {B_c: .5f} (Tesla)')

calculated spin density at muon site = -8.722000e-03 (bohr^-3) | contact field = -0.45730 (Tesla)


In [23]:
'_'.join(os.path.basename(up_file).split('.')[0:2])[:-2]

'Fe2P_QE_spinup_X'

move muon to origin, useful for hyperfine contact field calculations with QE

In [24]:
file = os.path.join(dpath, 'relax.out')
atoms = read_from_file(file, format='espresso-out', index=-1)

rlx = AseAtomsAdaptor.get_structure(atoms)

# get muon
mupos_rlx = rlx.frac_coords[rlx.atomic_numbers.index(1)]

rlx.translate_sites(
    range(rlx.num_sites), -mupos_rlx, frac_coords=True, to_unit_cell=False
)

for site in rlx:
    print(f"{site.species_string:<3} {site.a:14.9f} {site.b:14.9f} {site.c:14.9f}")

Ca     0.147298639    0.147298639   -0.000010350
Ca     0.624780375    0.624780375    0.499986135
Ca     0.619938009    0.619938009   -0.000008517
Ca     0.124817109    0.124817109    0.499984411
Ca     0.624558611    0.125352299    0.499985431
Ca     0.124064486    0.625468576   -0.000009340
Ca     0.125352299    0.624558611    0.499985431
Ca     0.625468576    0.124064486   -0.000009340
Ca     0.125617131    0.377354259    0.252623661
Ca     0.622643429   -0.125615103   -0.252653414
Ca     0.622649030   -0.125615701    0.252624146
Ca     0.125616536    0.377359862   -0.252652939
Ca     0.625041660    0.374960563   -0.250718077
Ca     0.128651806   -0.128647602    0.252111058
Ca     0.128649988   -0.128645781   -0.252122028
Ca     0.625042902    0.374959319    0.250689676
Ca     0.377354259    0.125617131    0.252623661
Ca    -0.125615103    0.622643429   -0.252653414
Ca    -0.125615701    0.622649030    0.252624146
Ca     0.377359862    0.125616536   -0.252652939
Ca    -0.128645781  