# I/O

In this example, we will show how to load various input types and to extract relevance informations

In [1]:
import numpy as np
from copy import deepcopy
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor

In [2]:
import sys
from pathlib import Path
ROOT = Path.cwd().parent.parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT)) 

from muonscripts.constants import constants
from muonscripts.io_tools.read import read_cif
from muonscripts.io_tools.read import read_from_file

import muonscripts.io_tools as ios
import muonscripts.io_tools.read_qe  as qe
import muonscripts.io_tools.read_elk  as elk

from muonscripts.io_tools.load_relax import load_relax
from muonscripts.io_tools.load_relax import save_relax_results
from muonscripts.io_tools.load_relax import load_relax_results
from muonscripts.io_tools.find_qe_files import select_groups
from muonscripts.io_tools.find_qe_files import get_relax_after_run
from muonscripts.io_tools.find_qe_files import print_relax_summary
from muonscripts.io_tools.find_qe_files import load_relax_from_folder


# ROOT, sys.path
print("Planck's Constant:", constants.H_PLANCK)

Planck's Constant: 6.62607015e-34


In [4]:
import os
dpath = '/home/misah/projects/muonscripts/examples/data'

load input structure formats

In [5]:
file=os.path.join(dpath, 'CaF2.cif')
read_cif(file)
read_from_file(file)

/home/misah/.virtualenvs/pyqm/lib/python3.10/site-packages/ase/io/cif.py:411: UserWarning: crystal system 'cubic' is not interpreted for space group Spacegroup(225, setting=1). This may result in wrong setting!
  warnings.warn(


Atoms(symbols='Ca4F8', pbc=True, cell=[5.45095, 5.45095, 5.45095], spacegroup_kinds=...)

In [6]:
file=os.path.join(dpath, 'CaF2.vasp')
read_cif(file)
read_from_file(file)

Atoms(symbols='Ca4F8', pbc=True, cell=[5.4509501457, 5.4509501457, 5.4509501457])

In [7]:
file=os.path.join(dpath, 'CaF2.vasp')
Structure.from_file(file)

Structure Summary
Lattice
    abc : 5.4509501457 5.4509501457 5.4509501457
 angles : 90.0 90.0 90.0
 volume : 161.96330486922204
      A : np.float64(5.4509501457) np.float64(0.0) np.float64(0.0)
      B : np.float64(0.0) np.float64(5.4509501457) np.float64(0.0)
      C : np.float64(0.0) np.float64(0.0) np.float64(5.4509501457)
    pbc : True True True
PeriodicSite: Ca (2.725, 2.725, 2.725) [0.5, 0.5, 0.5]
PeriodicSite: Ca (2.725, 0.0, 0.0) [0.5, 0.0, 0.0]
PeriodicSite: Ca (0.0, 2.725, 0.0) [0.0, 0.5, 0.0]
PeriodicSite: Ca (0.0, 0.0, 2.725) [0.0, 0.0, 0.5]
PeriodicSite: F (1.363, 4.088, 4.088) [0.25, 0.75, 0.75]
PeriodicSite: F (4.088, 1.363, 1.363) [0.75, 0.25, 0.25]
PeriodicSite: F (4.088, 1.363, 4.088) [0.75, 0.25, 0.75]
PeriodicSite: F (1.363, 4.088, 1.363) [0.25, 0.75, 0.25]
PeriodicSite: F (4.088, 4.088, 1.363) [0.75, 0.75, 0.25]
PeriodicSite: F (1.363, 1.363, 4.088) [0.25, 0.25, 0.75]
PeriodicSite: F (1.363, 1.363, 1.363) [0.25, 0.25, 0.25]
PeriodicSite: F (4.088, 4.088, 4.088) 

load QE input/output file

In [8]:
file = os.path.join(dpath, 'relax.in')
ios.read_qe.read_in(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [9]:
file = os.path.join(dpath, 'relax.out')
ios.read_qe.read_out(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.901900350679567, 10.901900350679567, 10.901900350679567], calculator=SinglePointDFTCalculator(...))

In [10]:
file = os.path.join(dpath, 'relax.in')
qe.read_in(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [11]:
file = os.path.join(dpath, 'relax.out')
qe.read_out(file)

Atoms(symbols='HCa32F64', pbc=True, cell=[10.901900350679567, 10.901900350679567, 10.901900350679567], calculator=SinglePointDFTCalculator(...))

In [12]:
file = os.path.join(dpath, 'relax.in')
read_from_file(file, format='espresso-in')

Atoms(symbols='HCa32F64', pbc=True, cell=[10.9019002914, 10.9019002914, 10.9019002914], initial_magmoms=...)

In [13]:
file = os.path.join(dpath, 'relax.out')
atoms = read_from_file(file, format='espresso-out', index=-1)

convert ase to pymatgen

In [14]:
rlx = AseAtomsAdaptor.get_structure(atoms)
rlx

Structure Summary
Lattice
    abc : 10.901900350679567 10.901900350679567 10.901900350679567
 angles : 90.0 90.0 90.0
 volume : 1295.7064600901604
      A : np.float64(10.901900350679567) np.float64(0.0) np.float64(0.0)
      B : np.float64(0.0) np.float64(10.901900350679567) np.float64(0.0)
      C : np.float64(0.0) np.float64(0.0) np.float64(10.901900350679567)
    pbc : True True True
PeriodicSite: Ca (2.969, 2.969, 2.725) [0.2723, 0.2723, 0.25]
PeriodicSite: Ca (8.174, 8.174, 8.176) [0.7498, 0.7498, 0.75]
PeriodicSite: Ca (8.121, 8.121, 2.726) [0.7449, 0.7449, 0.25]
PeriodicSite: Ca (2.723, 2.723, 8.176) [0.2498, 0.2498, 0.75]
PeriodicSite: Ca (8.172, 2.729, 8.176) [0.7496, 0.2504, 0.75]
PeriodicSite: Ca (2.715, 8.182, 2.726) [0.2491, 0.7505, 0.25]
PeriodicSite: Ca (2.729, 8.172, 8.176) [0.2504, 0.7496, 0.75]
PeriodicSite: Ca (8.182, 2.715, 2.726) [0.7505, 0.2491, 0.25]
PeriodicSite: Ca (2.732, 5.477, 5.48) [0.2506, 0.5024, 0.5026]
PeriodicSite: Ca (8.151, -0.006704, -0.02879) [0.7

convert pymatgen to ase

In [15]:
file=os.path.join(dpath, 'CaF2.vasp')
st = Structure.from_file(file)
atoms = AseAtomsAdaptor.get_atoms(st)
atoms

MSONAtoms(symbols='Ca4F8', pbc=True, cell=[5.4509501457, 5.4509501457, 5.4509501457])

load QE efg tensors from gipaw output file

In [16]:
file = os.path.join(dpath, 'V3Si_QE_EFG3x3x3_SITE_A.OUT')
efg_tensors = qe.read_efg(file)

efg_tensors[0]

array([[-8.62804611e+19,  0.00000000e+00, -1.14694029e+20],
       [ 0.00000000e+00, -2.97322139e+20,  0.00000000e+00],
       [-1.14694029e+20,  0.00000000e+00,  3.83602600e+20]])

load ELK output files: (geometry and EFG tensors)

In [17]:
file = os.path.join(dpath, 'MnSi_GEOMETRY.OUT')
elk.read_geom(file)

Atoms(symbols='Mn4Si4', pbc=True, cell=[4.566199937664733, 4.566199937664733, 4.566199937664733], initial_magmoms=...)

In [18]:
file = os.path.join(dpath, 'MnSi_EFG.OUT')
efg_tensors = elk.read_efg(file)

efg_tensors[0]

array([[-3.02274846e+04, -1.54534901e+20, -1.54534901e+20],
       [-1.54534901e+20, -3.12190144e+05, -1.54534901e+20],
       [-1.54534901e+20, -1.54534901e+20,  3.42417629e+05]])

remove numerical noise in efg tensors

In [19]:
remove_efg_noise=True
efg_noise_threshold=1e-8

tensors = []
for tensor in efg_tensors:
    if remove_efg_noise:
        max_element = np.max(np.abs(tensor))
        if max_element > 0:
            tensor[np.abs(tensor) < efg_noise_threshold * max_element] = 0.0
    tensors.append(tensor)

tensors[0]

array([[ 0.00000000e+00, -1.54534901e+20, -1.54534901e+20],
       [-1.54534901e+20,  0.00000000e+00, -1.54534901e+20],
       [-1.54534901e+20, -1.54534901e+20,  0.00000000e+00]])

query ALL 'relax' muon site calculations from a folder

In [20]:
folder = os.path.join(dpath, 'SZRO/query')

preview = True

pattern="*.out"
check_input = True
calc_types = "relax"


if preview:
    groups = get_relax_after_run(
        folder, 
        pattern=pattern, 
        check_input=check_input,
        calc_types=calc_types, 
        verbose=False,
    )
    print(f"\nPreview: {len(groups)} system group(s) found "
            f"(selection filters ignored in preview mode)\n")
    print_relax_summary(groups)


results = load_relax(
    path=folder,
    pattern=pattern,
    check_input=check_input,
    calc_types=calc_types,
    group_by_system=True,
    pymatgen=True,
    verbose=True,
    # **select_kwargs
)

file = 'SZRO_muonrelax_results.pkl'
file = os.path.join(dpath, file)
save_relax_results(results, file, fmt='pickle')


Preview: 1 system group(s) found (selection filters ignored in preview mode)

  H-O-Re-Sr-Zn  nat = 161  ntyp = 5  -> 12 converged runs
  ------------------------------------------
  1 distinct system(s), 12 converged run(s) total
Saved 12 result(s) to /home/misah/projects/muonscripts/examples/data/SZRO_muonrelax_results.pkl (pickle)


In [21]:
# folder = '/home/misah/projects/muonscripts/DATA/RVS'

# groups = get_relax_after_run(folder, check_input=True, calc_types='relax')
# print_relax_summary(groups)
# subset = None
# # subset = select_groups(groups, nat=(100, 200), min_runs=1)   # range + threshold, combinable
# subset = select_groups(groups, nat=(145, 145+1))   # range + threshold, combinable
# if subset:
#     print('='*50)
#     print_relax_summary(subset)


# results = load_relax(
#     path=folder,
#     pattern="*.out",
#     check_input=True,
#     calc_types="relax",
#     group_by_system=True,
#     pymatgen=True,
#     verbose=True,
#     # **select_kwargs
# )

In [22]:
# results[0]

In [23]:
# folder = '/home/misah/projects/muonscripts/DATA/RVS'
# folder = '/home/misah/projects/muonscripts/DATA/RVS/stable_sites_refined'

# groups = get_relax_after_run(folder, check_input=True, calc_types='relax')
# print_relax_summary(groups)
# subset = None
# # subset = select_groups(groups, nat=(100, 200), min_runs=1)   # range + threshold, combinable
# subset = select_groups(groups,)   # range + threshold, combinable
# if subset:
#     print_relax_summary(subset)


# results = load_relax(
#     path=folder,
#     pattern="*.out",
#     check_input=True,
#     calc_types="relax",
#     group_by_system=True,
#     pymatgen=True,
#     verbose=True,
#     # **select_kwargs
# )

In [24]:
# folder = '/home/misah/projects/muonscripts/DATA/RVS'
# folder = '/home/misah/projects/muonscripts/DATA/RVS/stable_sites_refined'
# folder = '/home/misah/projects/PERSONAL/DFT_MU/INITMU_vP_2x2x2/query'

# groups = get_relax_after_run(folder, check_input=True, calc_types='relax')
# print_relax_summary(groups)
# subset = None
# # subset = select_groups(groups, nat=(100, 200), min_runs=1)   # range + threshold, combinable
# subset = select_groups(groups,)   # range + threshold, combinable
# if subset:
#     print_relax_summary(subset)


# results = load_relax(
#     path=folder,
#     pattern="*.out",
#     check_input=True,
#     calc_types="relax",
#     group_by_system=True,
#     pymatgen=True,
#     verbose=True,
#     # **select_kwargs
# )

In [25]:
# results[0]

In [26]:
# import json, pickle
# from pymatgen.core import Structure

# file = 'SZRO_muRESULTS.json'
# file = os.path.join(dpath, file)
# with open(file, "r") as f:
#     json_data = json.load(f)

# file = 'SZRO_muRESULTS.pkl'
# file = os.path.join(dpath, file)
# with open(file, "rb") as f:
#     pkl_data = pickle.load(f)

# idx = 0

# pkl_data[idx]['rlxd_struct']

# entry = json_data[idx]['rlxd_struct']
# Structure.from_dict(entry["__pymatgen__"])